version: "3.9"
services:

  tool:
    build:
      context: ./
    container_name: template-tool
    environment:
      - AGENT_URL=http://agent/tools/register
    networks:
      - default

networks:

  default:
    external: true
    name: default-network
